---
layout: layouts/course-detail.html
tags: ["course"]
card_image: "/assets/images/courses/project-management-professional.webp"
card_category: "testing"
card_live: false
card_blurb: "Prepare for professional PMP credentials. Master project lifecycle frameworks, resource planning, and Scrum."
title: "PMP Certification Training — Live Online Course | RPAVault"
description: "Prepare for professional PMP credentials. Master project lifecycle frameworks, resource planning, and Scrum."
course_slug: "project-management-professional"
category: "Testing & QA Automation"
eyebrow: "Testing & QA Automation"
name: "PMP Certification Training"
lead: "Elevate your management career and target PMP certification. Learn resource scheduling, scope control boundaries, risk mitigations, quality management benchmarks, and agile Scrum execution models."
chips:
  - "⏱ 20-class roadmap"
  - "🎓 Live online sessions"
  - "💻 Live online"

duration: "20-class roadmap"
classes: "Live online sessions"
mode: "Live online"
level: "Beginner to Advanced"
support: "Recordings · doubt clearing · community support"

price_inr: "₹14,999"
price_inr_strike: "₹25,000"
price_usd: "$299"
price_usd_strike: "$499"
next_batch: "New batch planned — enroll now"

whatsapp_group_url: "/go/project-management-professional-whatsapp"
whatsapp_jobs_url: "/go/remote-jobs-whatsapp"
syllabus_pdf: "/assets/docs/project-management-professional-syllabus.pdf"

fit_check:
  - "Experienced project leads preparing for the official PMP exam"
  - "Software scrum masters wanting to align to PMI frameworks"
  - "Team managers transitioning to structured project steering roles"

what_you_get:
  - "Comprehensive analysis of the PMBOK Guide standards"
  - "Creating Project Charters, resource scopes, and timeline benchmarks"
  - "Handling agile sprint boards and task allocations"
  - "Full practice simulation modules for PMP examinations"

curriculum:
  - phase: "Phase 1 · Frameworks Core & System Schemas"
    duration: "Module 1"
    outcome: "Assess scope specifications and build system layouts."
    sessions:
      - num: "Class 1"
        title: "Core Methodologies and PMP Certification Training Framework Setup"
        details: "Analyze core workflow architectures, configure client utilities, and define project templates."
      - num: "Class 2"
        title: "Writing System Project Plans and Setup Instructions"
        details: "Write system setups instructions, configure environment packages, and document requirements."
      - num: "Class 3"
        title: "Navigating Terminal Commands and Global Settings"
        details: "Execute terminal commands controls, manage local configuration files, and setup logins."
      - num: "Class 4"
        title: "Gathering Project Specifications and Business Scopes"
        details: "Isolate business objectives, document functional targets, and outline process flow charts."
      - num: "Class 5"
        title: "Creating System Blueprints, Schemas, and Test Plans"
        details: "Design complete test plans spreadsheets, compile architecture layouts, and assess risk parameters."
  - phase: "Phase 2 · Scenarios Development & UI Selectors"
    duration: "Module 2"
    outcome: "Configure selector matchers and validate form validations."
    sessions:
      - num: "Class 6"
        title: "Structuring Reusable Modules and Template Blocks"
        details: "Structure reusable logic components directories, default variables sheets, and templates."
      - num: "Class 7"
        title: "Developing Detailed Test Cases, Use Cases, or Layouts"
        details: "Write detailed step-by-step test scripts scenarios, specify expected targets, and handle data maps."
      - num: "Class 8"
        title: "Spying Interface Selectors and Locating Elements"
        details: "Identify browser tags elements, inspect coordinates selectors, and configure selector actions."
      - num: "Class 9"
        title: "Asserting Expected Outputs and Validating Forms Input"
        details: "Compare execution results against expected targets, isolate errors, and capture stack logs."
      - num: "Class 10"
        title: "Handling Iterative Loops and Dynamic Parameters"
        details: "Implement index variables trackers, control loop steps, and parameterize input ranges."
  - phase: "Phase 3 · Pipeline Integrations & Scheduled Jobs"
    duration: "Module 3"
    outcome: "Trigger verification suites on continuous delivery runs."
    sessions:
      - num: "Class 11"
        title: "Connecting external Data Tables and REST Endpoint Feeds"
        details: "Read data records tables from Excel sheets, populate API requests payloads, and verify status codes."
      - num: "Class 12"
        title: "Debugging Execution Errors and Resolving System Lockups"
        details: "Inspect runtime crash points, identify thread locks blockers, and apply recovery scripts steps."
      - num: "Class 13"
        title: "Orchestrating Scheduled Test Run Configurations"
        details: "Configure automated test suite trigger schedules, verify reporting locations, and track email charts."
      - num: "Class 14"
        title: "Integrating Test Suites with CI/CD Build Pipelines"
        details: "Inject automated verification test runs tasks into CI/CD build scripts pipelines and gate releases."
      - num: "Class 15"
        title: "Configuring Metrics Dashboards and Performance Telemetry"
        details: "Build execution history dashboards, collect system load telemetry, and review log summaries."
  - phase: "Phase 4 · Quality Assurance Gates & Sign-off"
    duration: "Module 4"
    outcome: "Present incident maps and compile deployment blueprints."
    sessions:
      - num: "Class 16"
        title: "Enforcing Security Privilege Settings and Encryption Keys"
        details: "Implement secure credential key parameters, configure logins access roles, and audit access permissions."
      - num: "Class 17"
        title: "Running User Acceptance Testing (UAT) Checklists"
        details: "Verify business user stories scenarios, document exceptions lists, and verify target acceptance inputs."
      - num: "Class 18"
        title: "Incident Management, Issue Loggings, and Bug Tracking"
        details: "File detailed bug reports, configure issue status transitions, and resolve developer code blocks."
      - num: "Class 19"
        title: "Release Packing and Deployment Migration Profiles"
        details: "Compile release blueprints documents, export packaged models files, and verify versions mappings."
      - num: "Class 20"
        title: "PMP Certification Training Final Capstone Project Verification & Mock Interviews"
        details: "Present complete system designs configurations, explain verification scripts outputs, and get sign-off."
---
