declare module 'lucide-react' {
  import * as React from 'react';
  export interface LucideProps extends React.SVGProps<SVGSVGElement> {
    size?: number | string;
    strokeWidth?: number | string;
    color?: string;
  }
  export type Icon = React.FC<LucideProps>;
  export const CheckSquare: Icon;
  export const Lock: Icon;
  export const User: Icon;
  export const ArrowRight: Icon;
  export const Loader2: Icon;
  export const Calendar: Icon;
  export const CalendarDays: Icon;
  export const CalendarCheck: Icon;
  export const AlertCircle: Icon;
  export const Inbox: Icon;
  export const CheckCircle2: Icon;
  export const Tag: Icon;
  export const Users: Icon;
  export const LogOut: Icon;
  export const Moon: Icon;
  export const Sun: Icon;
  export const Plus: Icon;
  export const Clock: Icon;
  export const Repeat: Icon;
  export const Check: Icon;
  export const ExternalLink: Icon;
  export const X: Icon;
  export const Trash2: Icon;
  export const AlertTriangle: Icon;
  export const Database: Icon;
  export const Key: Icon;
  export const CheckCircle: Icon;
  export const Sparkles: Icon;
  export const RotateCw: Icon;
  export const Menu: Icon;
  export const Search: Icon;
  export const Link: Icon;
  export const Eye: Icon;
  export const EyeOff: Icon;
  export const UserCheck: Icon;
  export const FileText: Icon;
  export const ChevronDown: Icon;
  export const ChevronRight: Icon;
  export const History: Icon;
  export const MessageSquare: Icon;
  export const Image: Icon;
  export const AtSign: Icon;
  export const Send: Icon;
  export const Cloud: Icon;
}
