---
layout: layouts/course-detail.html
tags: ["course"]
card_image: "/assets/images/courses/power-bi.webp"
card_category: "data"
card_live: false
card_blurb: "Power BI Desktop to Service — Power Query, modelling, basic to advanced DAX and 4 portfolio projects. PL-300 aligned."
title: "Power BI — Live Online Course | RPAVault"
description: "Power BI Desktop to Service — Power Query, modelling, basic to advanced DAX and 4 portfolio projects. PL-300 aligned."
course_slug: "power-bi"

category: "Data & Business Intelligence"
eyebrow: "Data & Business Intelligence"
name: "Power BI"
lead: "Build interactive dashboards that stand out in interviews. Master the entire Power BI desktop to service pipeline: clean complex datasets with Power Query, design star-schema relationships, write advanced DAX logic, and publish PL-300 aligned reports."
chips:
  - "⏱ 5 modules"
  - "🎓 Live online sessions"
  - "💻 Live online"

duration: "5 modules"
classes: "Live online sessions"
mode: "Live online"
level: "Beginner friendly"
support: "Recordings · doubt clearing · community support"

price_inr: "₹12,000"
price_inr_strike: "₹18,000"
price_usd: "$249"
price_usd_strike: "$349"
payment_inr_url: "https://tally.so/r/waa7gZ"
payment_usd_url: "https://tally.so/r/waa7gZ"
next_batch: "Open for interest — contact us for dates"

whatsapp_group_url: "/go/power-bi-whatsapp"
whatsapp_jobs_url: "/go/remote-jobs-whatsapp"

fit_check:
  - "Excel-heavy professionals ready to upgrade to real BI"
  - "Freshers targeting data analyst roles"
  - "Managers and consultants who need self-service analytics"
  - "Anyone preparing for the Microsoft PL-300 certification"

what_you_get:
  - "Power BI Desktop and Power Query data preparation"
  - "Data modelling: relationships, star schemas, best practices"
  - "DAX from first measure to advanced time intelligence"
  - "Power BI Service: publishing, refresh, apps and mobile"
  - "4 end-to-end projects for your portfolio"

curriculum:
  - phase: "Phase 1: Getting Started & Power Query"
    duration: "Classes 1-5"
    outcome: "Outcome: You can connect to sources and clean messy data"
    sessions:
      - num: "Class 1"
        title: "Introduction to Power BI Architecture"
        details: "Overview of Power BI Desktop, Service, and Mobile. Installation and interface tour."
      - num: "Class 2"
        title: "Connecting to Data Sources"
        details: "Importing data from Excel, CSV, SQL Server, and Web sources. Import vs DirectQuery."
      - num: "Class 3"
        title: "Power Query Editor Basics"
        details: "Data profiling, changing data types, removing duplicates, and filtering rows."
      - num: "Class 4"
        title: "Advanced Data Transformations"
        details: "Pivoting, unpivoting, splitting columns, and conditional columns in Power Query."
      - num: "Class 5"
        title: "Combining Data"
        details: "Appending queries and merging queries (joins) to create flattened tables."
  - phase: "Phase 2: Data Modeling"
    duration: "Classes 6-10"
    outcome: "Outcome: You can build optimized relational models"
    sessions:
      - num: "Class 6"
        title: "Data Modeling Fundamentals"
        details: "Understanding Fact and Dimension tables. The importance of Star Schema design."
      - num: "Class 7"
        title: "Creating Relationships"
        details: "Managing active and inactive relationships, cross-filter direction, and cardinality."
      - num: "Class 8"
        title: "Creating a Date Table"
        details: "Why a Date table is essential. Building a robust Calendar table using DAX or Power Query."
      - num: "Class 9"
        title: "Hierarchies and Grouping"
        details: "Creating drill-down hierarchies and grouping data bins for better analysis."
      - num: "Class 10"
        title: "Optimizing the Model"
        details: "Hiding columns from report view, formatting data correctly, and performance tuning basics."
  - phase: "Phase 3: DAX (Data Analysis Expressions)"
    duration: "Classes 11-15"
    outcome: "Outcome: You can write complex analytical formulas"
    sessions:
      - num: "Class 11"
        title: "Introduction to DAX"
        details: "Calculated Columns vs Measures. Understanding Row Context vs Filter Context."
      - num: "Class 12"
        title: "Core Aggregation Functions"
        details: "Using SUM, AVERAGE, MIN, MAX, COUNTROWS, and DISTINCTCOUNT."
      - num: "Class 13"
        title: "The CALCULATE Function"
        details: "Mastering CALCULATE to manipulate filter context dynamically in your reports."
      - num: "Class 14"
        title: "Iterator Functions (The 'X' Functions)"
        details: "Understanding SUMX, AVERAGEX, and row-by-row calculations."
      - num: "Class 15"
        title: "Time Intelligence Functions"
        details: "Calculating YTD, QTD, MTD, and YoY comparisons using TOTALYTD and SAMEPERIODLASTYEAR."
  - phase: "Phase 4: Visualizations & Power BI Service"
    duration: "Classes 16-20"
    outcome: "Outcome: You can design stunning dashboards and publish them"
    sessions:
      - num: "Class 16"
        title: "Building Core Visuals"
        details: "Bar charts, line charts, matrices, cards, and formatting visual properties."
      - num: "Class 17"
        title: "Advanced Visualization Techniques"
        details: "Using Tooltips, Bookmarks, Buttons, and conditional formatting for interactive reports."
      - num: "Class 18"
        title: "Publishing to Power BI Service"
        details: "Workspaces, Dashboards vs Reports, and pinning visuals."
      - num: "Class 19"
        title: "Data Refresh and Gateways"
        details: "Setting up scheduled refresh and configuring the On-Premises Data Gateway."
      - num: "Class 20"
        title: "Security and Capstone Project"
        details: "Implementing Row-Level Security (RLS) and presenting your final comprehensive dashboard."

trainers:
  - name: "Piyush Agrawal"
    avatar: "PA"
    role: "BI & Data Trainer · 14+ years · 8000+ learners trained"
    bio: "14+ years across the Microsoft data stack, having trained 8,000+ learners in SQL, MSBI and Power BI."
    linkedin: "https://www.linkedin.com/in/piyush-agrawal-a9738335/"
    highlights:
      - "14+ years Microsoft data platform experience"
      - "8,000+ learners trained"
      - "PL-300-aligned, project-first curriculum"

faqs:
  - q: "Do I need SQL or Excel first?"
    a: "No hard prerequisite — the course starts from fundamentals. Excel familiarity helps; adding our SQL Server Masterclass makes you a stronger analyst."
  - q: "Does this prepare me for PL-300?"
    a: "Yes — the curriculum is aligned with Microsoft's PL-300 Data Analyst certification topics."
  - q: "How much DAX is covered?"
    a: "Two full modules — from your first measure to advanced time-intelligence patterns used in real dashboards."
  - q: "What are the fees and dates?"
    a: "Batches are scheduled on demand — request a callback and we'll share the current fee and next start date."
---
