// RPAVault short links — served from Cloudflare KV (binding: LINKS)
// Managed from the Google Sheet "links" tab via Apps Script sync.
export async function onRequest(context) {
  const { params, env, request } = context;
  const slug = String(params.slug || "").toLowerCase();

  // Prevent routing loops for the main redirect landing/resolver page
  if (slug === "index.html" || slug === "index" || !slug) {
    return await context.next();
  }

  const raw = env.LINKS ? await env.LINKS.get(slug) : null;
  
  if (!raw) {
    // Fallback to static assets (e.g. static redirect pages generated by Eleventy)
    const response = await context.next();
    if (response.status === 404) {
      const url = new URL(request.url);
      return Response.redirect(`${url.origin}/go/?slug=${encodeURIComponent(slug)}`, 302);
    }
    return response;
  }
  
  let link;
  try { link = JSON.parse(raw); } catch (e) { link = { destination: raw }; }
  const ua = (request.headers.get("user-agent") || "").toLowerCase();
  const isPreviewBot = /(facebookexternalhit|whatsapp|twitterbot|linkedinbot|telegrambot|slackbot|discordbot|pinterest|skypeuripreview|vkshare|redditbot)/.test(ua);
  if (!isPreviewBot) {
    return Response.redirect(link.destination, 302);
  }
  
  const urlObj = new URL(request.url);
  const origin = urlObj.origin;
  const esc = (s) => String(s || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/"/g, "&quot;");
  const title = esc(link.og_title || link.title || "RPAVault");
  const desc = esc(link.og_description || link.description || "Automation consultancy, enterprise automation and IT training.");
  const img = esc(link.og_image || link.image || `${origin}/assets/images/og-image.png`);
  const url = `${origin}/go/${esc(slug)}`;
  const html = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<title>${title}</title>
<meta name="robots" content="noindex, nofollow">
<meta name="description" content="${desc}">
<meta property="og:type" content="website">
<meta property="og:title" content="${title}">
<meta property="og:description" content="${desc}">
<meta property="og:image" content="${img}">
<meta property="og:url" content="${url}">
<meta name="twitter:card" content="summary_large_image">
<meta http-equiv="refresh" content="0;url=${esc(link.destination)}">
</head><body>Redirecting…</body></html>`;
  return new Response(html, { headers: { "content-type": "text/html; charset=utf-8", "x-robots-tag": "noindex, nofollow", "cache-control": "no-store" } });
}
