---
layout: layouts/course-detail.html
tags: ["course"]
card_image: "/assets/images/courses/power-automate.webp"
card_category: "rpa"
card_live: false
card_blurb: "Automate desktop and web workflows. Master cloud flows, desktop flows, UI automation, and AI builder integrations."
title: "Microsoft Power Automate — Live Online Course | RPAVault"
description: "Automate desktop and web workflows. Master cloud flows, desktop flows, UI automation, and AI builder integrations."
course_slug: "power-automate"
category: "RPA & Agentic Automation"
eyebrow: "RPA & Agentic Automation"
name: "Microsoft Power Automate"
lead: "Orchestrate modern API-first and UI-based automations with Microsoft Power Automate. Build sophisticated desktop flows, trigger cloud events, process documents with AI Builder, and implement custom actions."
chips:
  - "⏱ 20-class roadmap"
  - "🎓 Live online sessions"
  - "💻 Live online"

duration: "20-class roadmap"
classes: "Live online sessions"
mode: "Live online"
level: "Beginner to Advanced"
support: "Recordings · doubt clearing · community support"

price_inr: "₹14,999"
price_inr_strike: "₹25,000"
price_usd: "$299"
price_usd_strike: "$499"
next_batch: "New batch planned — enroll now"

whatsapp_group_url: "/go/power-automate-whatsapp"
whatsapp_jobs_url: "/go/remote-jobs-whatsapp"
syllabus_pdf: "/assets/docs/power-automate-syllabus.pdf"

fit_check:
  - "Office operators transitioning routine processes to cloud flows"
  - "Power Platform developers adding desktop RPA skills to their projects"
  - "IT professionals structuring enterprise-grade automated approval queues"

what_you_get:
  - "Hands-on building of Cloud Flows and Desktop Flows (PAD)"
  - "Built-in Microsoft connectors for SharePoint, Outlook, and Teams"
  - "Integrating document parser logic using AI Builder models"
  - "PL-500 Certification roadmap and practice exam guides"

curriculum:
  - phase: "Phase 1 · Foundations & Architecture"
    duration: "Module 1"
    outcome: "Master the basic syntax and process flow design."
    sessions:
      - num: "Class 1"
        title: "Introduction to RPA & Microsoft Power Automate Architecture"
        details: "Learn background processes orchestration, robot nodes runtime variables, and standard workspace grids."
      - num: "Class 2"
        title: "Environment Configuration and Developer Interface"
        details: "Configure system dependencies, interface panels, local folder rules, and basic debugger limits."
      - num: "Class 3"
        title: "Variables, Data Types, and Expression Operators"
        details: "Initialize data arrays, declare scopes, perform string conversions, and parse boolean values."
      - num: "Class 4"
        title: "Designing Control Workflows & Decision Branches"
        details: "Structure conditional routing shapes, build multi-path decisions, and monitor logic flows."
      - num: "Class 5"
        title: "Handling Collections, Arrays, and Input Parameters"
        details: "Map arguments fields, bind values, write dictionary properties, and debug loop iterations."
  - phase: "Phase 2 · Interface Modeler & UI Spying"
    duration: "Module 2"
    outcome: "Spy and automate browser forms and legacy controls."
    sessions:
      - num: "Class 6"
        title: "UI Object Spying and Element Identifiers"
        details: "Master the spying modeller pane to capture tag configurations, check tree layers, and index lists."
      - num: "Class 7"
        title: "Automating Web Applications with HTML Selectors"
        details: "Spy HTML browser forms elements, input text attributes, and trigger form submits asynchronously."
      - num: "Class 8"
        title: "Automating Desktop Applications with Win32 Controls"
        details: "Automate legacy Windows programs using desktop handles, active grids, and coordinates offsets."
      - num: "Class 9"
        title: "Dynamic Selectors, Wildcards, and Attribute Regular Expressions"
        details: "Implement dynamic selector matchers, clean attributes wildcards, and write regex expressions."
      - num: "Class 10"
        title: "Reusable Sub-processes and Object Modules Creation"
        details: "Package process actions into clean reusable modules, specify input parameters, and build libraries."
  - phase: "Phase 3 · Advanced Queues & Exceptions"
    duration: "Module 3"
    outcome: "Orchestrate transactional queues with try-catch recover blocks."
    sessions:
      - num: "Class 11"
        title: "Enterprise Work Queues & Priority Mappings"
        details: "Establish transactional queue models, define prioritization levels, and manage retry allocations."
      - num: "Class 12"
        title: "Queue Status Tagging, Filter Conditions, and Loops"
        details: "Apply status tags, query active transaction rows, execute loops, and archive completed records."
      - num: "Class 13"
        title: "Error Handling Strategies and Try-Catch Blocks"
        details: "Implement recovery scopes, write logs, isolate error stack traces, and recover browser states."
      - num: "Class 14"
        title: "Configuring Business Exception Validations"
        details: "Throw custom business validations exceptions, prevent incorrect inputs processing, and notify users."
      - num: "Class 15"
        title: "Credentials Vault Integration & Secrets Management"
        details: "Integrate secure lockers, fetch encrypted login credentials fields, and decrypt variables safely."
  - phase: "Phase 4 · Admin Control Room & Deployments"
    duration: "Module 4"
    outcome: "Schedule and package release bots for production runners."
    sessions:
      - num: "Class 16"
        title: "Web APIs, HTTP Actions, and JSON Deserialization"
        details: "Build HTTP requests scripts to connect to REST endpoints, pass authorization tokens, and parse JSON."
      - num: "Class 17"
        title: "Deploying to Run Schedule Dashboards"
        details: "Publish local bot packages to orchestrator platforms, schedule runs calendar, and verify execution logs."
      - num: "Class 18"
        title: "Resource PC Scaling and Runner Configurations"
        details: "Configure parallel bot runner machines, monitor active nodes load, and configure failover scripts."
      - num: "Class 19"
        title: "Exporting Bot Packages and Release Deployments"
        details: "Compile deployment package files, verify dependencies versions, and execute dev-to-prod tasks."
      - num: "Class 20"
        title: "Microsoft Power Automate Capstone Automation Project Audit & Live Review"
        details: "Deploy a complete multi-step automated transaction scenario, verify email alerts, and receive sign-off."
---
