---
layout: layouts/course-detail.html
tags: ["course"]
card_image: "/assets/images/courses/microsoft-azure.webp"
card_category: "cloud"
card_live: false
card_blurb: "Master Azure cloud services and solutions. Build virtual networks, app services, SQL databases, and prepare for AZ-104."
title: "Microsoft Azure — Live Online Course | RPAVault"
description: "Master Azure cloud services and solutions. Build virtual networks, app services, SQL databases, and prepare for AZ-104."
course_slug: "microsoft-azure"
category: "Cloud Computing"
eyebrow: "Cloud Computing"
name: "Microsoft Azure"
lead: "Design enterprise cloud solutions on Microsoft Azure. Set up secure virtual networks, run highly scalable App Services, configure managed databases, and build identity solutions using Microsoft Entra ID."
chips:
  - "⏱ 20-class roadmap"
  - "🎓 Live online sessions"
  - "💻 Live online"

duration: "20-class roadmap"
classes: "Live online sessions"
mode: "Live online"
level: "Beginner to Advanced"
support: "Recordings · doubt clearing · community support"

price_inr: "₹14,999"
price_inr_strike: "₹25,000"
price_usd: "$299"
price_usd_strike: "$499"
next_batch: "New batch planned — enroll now"

whatsapp_group_url: "/go/microsoft-azure-whatsapp"
whatsapp_jobs_url: "/go/remote-jobs-whatsapp"
syllabus_pdf: "/assets/docs/microsoft-azure-syllabus.pdf"

fit_check:
  - "System operators transitioning Windows servers to Azure nodes"
  - "Network engineers structuring hybrid corporate network connections"
  - "IT students preparing for the AZ-104 Azure Administrator exam"

what_you_get:
  - "Azure Portal, Cloud Shell, and ARM template deployment setups"
  - "Virtual network configuration including peering and NSG rules"
  - "Configuring App Service slots, Azure Blob storage, and Entra ID"
  - "AZ-104 Azure Administrator Certification alignment"

curriculum:
  - phase: "Phase 1 · Identity & Cloud Networks"
    duration: "Module 1"
    outcome: "Design virtual private networks and secure access gates."
    sessions:
      - num: "Class 1"
        title: "Cloud Fundamentals & Microsoft Azure Architecture"
        details: "Understand global regions structures, service divisions, availability zones, and billing boundaries."
      - num: "Class 2"
        title: "Configuring Identities, Roles, Policy Permissions"
        details: "Configure IAM user databases, enforce MFA triggers, write custom policies, and delegate service roles."
      - num: "Class 3"
        title: "Designing Virtual Private Networks and Subnet Divisions"
        details: "Design custom virtual networks, assign IP cidr layouts, configure public subnets, and peer networks."
      - num: "Class 4"
        title: "Route Tables, Internet Gateways, and Network NAT Rules"
        details: "Create network internet gateways tables, allocate elastic static IPs, and map network translations."
      - num: "Class 5"
        title: "Security Policies: Access Control Lists (NACL) and Port Rules"
        details: "Enforce subnet boundaries protections using NACL rules and configure virtual instance Security Groups."
  - phase: "Phase 2 · Compute Scaling & Relational Storage"
    duration: "Module 2"
    outcome: "Provision compute nodes, auto-scaling groups and databases."
    sessions:
      - num: "Class 6"
        title: "Provisioning Compute Nodes and Scale Instances"
        details: "Launch virtual instances types, set up ssh keys, and run initialization bash scripts."
      - num: "Class 7"
        title: "Managed Block Storage volumes, Snapshots, and Mounts"
        details: "Mount virtual block volumes, format filesystem formats, allocate IOPS levels, and backup snapshots."
      - num: "Class 8"
        title: "Cloud Buckets Storage Tiers, Policies, and CDN Pipelines"
        details: "Configure cloud bucket folders, set public blocks, define life policies, and configure CDN caches."
      - num: "Class 9"
        title: "Configuring High Availability Load Balancers & Target Pools"
        details: "Deploy application load balancers, register virtual targets, and customize health checks thresholds."
      - num: "Class 10"
        title: "Setting Auto-Scaling Boundaries and Metrics Rules"
        details: "Define autoscaling group schedules, configure system cpu usage alerts, and verify node scaling."
  - phase: "Phase 3 · Infrastructure as Code & Containers"
    duration: "Module 3"
    outcome: "Write declarative templates and pack docker container stacks."
    sessions:
      - num: "Class 11"
        title: "Managed Database Instances Setup & Relational Replication"
        details: "Deploy managed relational database configurations, enable multi-AZ backups, and optimize read speeds."
      - num: "Class 12"
        title: "Writing Declarative Infrastructure as Code (IaC) Templates"
        details: "Translate infrastructure architectures into clean code files templates using standard tools."
      - num: "Class 13"
        title: "Containerizing Applications using Dockerfiles"
        details: "Write container layout files, specify base images, copy source directories, and build image packages."
      - num: "Class 14"
        title: "Orchestrating Container Stacks inside Docker Compose"
        details: "Define multi-service configuration YAML stacks, map network links, and expose public ports."
      - num: "Class 15"
        title: "Kubernetes Clusters Architecture, Pods, and Deployments"
        details: "Setup local cluster nodes, launch pods spec files, configure replicas, and apply namespace policies."
  - phase: "Phase 4 · CI/CD Automation & Pipelines Deployment"
    duration: "Module 4"
    outcome: "Orchestrate YAML builds pipelines and compile telemetry."
    sessions:
      - num: "Class 16"
        title: "Kubernetes Ingress Controllers, Service Types, and Secrets"
        details: "Configure cluster ingress rules, handle DNS routing maps, and inject secret credentials files."
      - num: "Class 17"
        title: "Writing Reusable Configuration Roles and Playbooks"
        details: "Write automated playbook files, handle variables scopes, import configurations, and manage roles."
      - num: "Class 18"
        title: "Multi-stage CI/CD Pipelines YAML Configurations"
        details: "Build CI/CD deployment flow structures, trigger automated builds on git events, and run code checkers."
      - num: "Class 19"
        title: "Automating Code Build Compilations and Telemetry Logs"
        details: "Deploy application packages to container clusters, aggregate system output logs, and set alert logs."
      - num: "Class 20"
        title: "Microsoft Azure Production Deployments Capstone Case Setup & Review"
        details: "Deploy a complete high-availability cloud architecture, execute failure simulations, and audit records."
---
